@startuml HashTableOA_CPP
class Cell<Key, Value> <<struct>> {
  + key: Key
  + value: Value
  + isOccupied: bool
  + isDeleted: bool
  
  + Cell()
}

class HashTableOA<Key, Value> {
  - table: Cell<Key, Value>*
  - size: size_t
  - capacity: size_t
  - loadFactor: float
  - a: int
  - b: int
  - p: int
  
  + HashTableOA(capacity: int)
  + HashTableOA(other: const HashTableOA&)
  + operator=(other: const HashTableOA&): HashTableOA&
  + ~HashTableOA()
  + insert(key: const Key&, value: const Value&): bool
  + isPresent(key: const Key&): bool
  + find(key: const Key&): Value
  + remove(key: const Key&): bool
  + print(): void
  + clean(): void
  + getSize(): size_t
  + getCapacity(): size_t
  + getLoadFactor(): float
  + saveText(filename: const string&): void
  + loadText(filename: const string&): void
  + saveBinary(filename: const string&): void
  + loadBinary(filename: const string&): void
  - init(): void
  - h1(key: const Key&): size_t
  - swap(other: HashTableOA&): void
}

HashTableOA *-- Cell : contains

@enduml